import { EPSILON } from './common.js';
import { Vec2 } from './vec2.js';
import { Vec4 } from './vec4.js';
import { Mat4Like } from './mat4.js';

/**
 * A 3 dimensional vector given as a {@link Vec3}, a 3-element Float32Array, or
 * an array of 3 numbers.
 */
export type Vec3Like = [number, number, number] | Float32Array;

 /**
  * 3 Dimensional Vector
  */
export class Vec3 extends Float32Array {
  /**
  * The number of bytes in a {@link Vec3}.
  */
   static readonly BYTE_LENGTH = 3 * Float32Array.BYTES_PER_ELEMENT;

  /**
  * Create a {@link Vec3}.
  */
  constructor(...values: [Readonly<Vec3Like>, number?] | number[]) {
    switch(values.length) {
      case 3:
        super(values); break;
      case 2:
      case 1:
        super(values[0] as ArrayBufferLike, values[1] ?? 0, 3); break;
      default:
        super(3); break;
    }
  }

  //============
  // Attributes
  //============

  // Getters to make component access read better.
  // These are likely to be a little bit slower than direct array access.

  /**
  * The x component of the vector. Equivalent to `this[0];`
  */
  get x(): number { return this[0]; }
  set x(value: number) { this[0] = value; }

  /**
  * The y component of the vector. Equivalent to `this[1];`
  */
  get y(): number { return this[1]; }
  set y(value: number) { this[1] = value; }

  /**
  * The z component of the vector. Equivalent to `this[2];`
  */
  get z(): number { return this[2]; }
  set z(value: number) { this[2] = value; }

  /**
   * The magnitude (length) of this.
   * Equivalent to `Vec3.magnitude(this);`
   *
   * Magnitude is used because the `length` attribute is already defined by
   * `Float32Array` to mean the number of elements in the array.
   */
  get magnitude(): number {
    const x = this[0];
    const y = this[1];
    const z = this[2];
    return Math.sqrt(x * x + y * y + z * z);
  }
  /**
   * Alias for {@link Vec3.magnitude}
   */
  get mag(): number { return this.magnitude; }

  /**
   * The squared magnitude (length) of `this`.
   * Equivalent to `Vec3.squaredMagnitude(this);`
   */
  get squaredMagnitude(): number {
    const x = this[0];
    const y = this[1];
    const z = this[2];
    return x * x + y * y + z * z;
  }
  /**
   * Alias for {@link Vec3.squaredMagnitude}
   */
  get sqrMag(): number { return this.squaredMagnitude; }

  /**
   * A string representation of `this`
   * Equivalent to `Vec3.str(this);`
   */
  get str(): string {
    return Vec3.str(this);
  }

  //====================
  // Swizzle attributes
  //====================

  // The contents of the following section are autogenerated by scripts/gen-swizzle.js and should
  // not be modified by hand.
  // [Swizzle Autogen]

  /** @group Swizzle */ get xx(): Vec2 { return new Vec2(this[0], this[0]); }
  /** @group Swizzle */ get xy(): Vec2 { return new Vec2(this[0], this[1]); }
  /** @group Swizzle */ get xz(): Vec2 { return new Vec2(this[0], this[2]); }
  /** @group Swizzle */ get yx(): Vec2 { return new Vec2(this[1], this[0]); }
  /** @group Swizzle */ get yy(): Vec2 { return new Vec2(this[1], this[1]); }
  /** @group Swizzle */ get yz(): Vec2 { return new Vec2(this[1], this[2]); }
  /** @group Swizzle */ get zx(): Vec2 { return new Vec2(this[2], this[0]); }
  /** @group Swizzle */ get zy(): Vec2 { return new Vec2(this[2], this[1]); }
  /** @group Swizzle */ get zz(): Vec2 { return new Vec2(this[2], this[2]); }
  /** @group Swizzle */ get xxx(): Vec3 { return new Vec3(this[0], this[0], this[0]); }
  /** @group Swizzle */ get xxy(): Vec3 { return new Vec3(this[0], this[0], this[1]); }
  /** @group Swizzle */ get xxz(): Vec3 { return new Vec3(this[0], this[0], this[2]); }
  /** @group Swizzle */ get xyx(): Vec3 { return new Vec3(this[0], this[1], this[0]); }
  /** @group Swizzle */ get xyy(): Vec3 { return new Vec3(this[0], this[1], this[1]); }
  /** @group Swizzle */ get xyz(): Vec3 { return new Vec3(this[0], this[1], this[2]); }
  /** @group Swizzle */ get xzx(): Vec3 { return new Vec3(this[0], this[2], this[0]); }
  /** @group Swizzle */ get xzy(): Vec3 { return new Vec3(this[0], this[2], this[1]); }
  /** @group Swizzle */ get xzz(): Vec3 { return new Vec3(this[0], this[2], this[2]); }
  /** @group Swizzle */ get yxx(): Vec3 { return new Vec3(this[1], this[0], this[0]); }
  /** @group Swizzle */ get yxy(): Vec3 { return new Vec3(this[1], this[0], this[1]); }
  /** @group Swizzle */ get yxz(): Vec3 { return new Vec3(this[1], this[0], this[2]); }
  /** @group Swizzle */ get yyx(): Vec3 { return new Vec3(this[1], this[1], this[0]); }
  /** @group Swizzle */ get yyy(): Vec3 { return new Vec3(this[1], this[1], this[1]); }
  /** @group Swizzle */ get yyz(): Vec3 { return new Vec3(this[1], this[1], this[2]); }
  /** @group Swizzle */ get yzx(): Vec3 { return new Vec3(this[1], this[2], this[0]); }
  /** @group Swizzle */ get yzy(): Vec3 { return new Vec3(this[1], this[2], this[1]); }
  /** @group Swizzle */ get yzz(): Vec3 { return new Vec3(this[1], this[2], this[2]); }
  /** @group Swizzle */ get zxx(): Vec3 { return new Vec3(this[2], this[0], this[0]); }
  /** @group Swizzle */ get zxy(): Vec3 { return new Vec3(this[2], this[0], this[1]); }
  /** @group Swizzle */ get zxz(): Vec3 { return new Vec3(this[2], this[0], this[2]); }
  /** @group Swizzle */ get zyx(): Vec3 { return new Vec3(this[2], this[1], this[0]); }
  /** @group Swizzle */ get zyy(): Vec3 { return new Vec3(this[2], this[1], this[1]); }
  /** @group Swizzle */ get zyz(): Vec3 { return new Vec3(this[2], this[1], this[2]); }
  /** @group Swizzle */ get zzx(): Vec3 { return new Vec3(this[2], this[2], this[0]); }
  /** @group Swizzle */ get zzy(): Vec3 { return new Vec3(this[2], this[2], this[1]); }
  /** @group Swizzle */ get zzz(): Vec3 { return new Vec3(this[2], this[2], this[2]); }
  /** @group Swizzle */ get xxxx(): Vec4 { return new Vec4(this[0], this[0], this[0], this[0]); }
  /** @group Swizzle */ get xxxy(): Vec4 { return new Vec4(this[0], this[0], this[0], this[1]); }
  /** @group Swizzle */ get xxxz(): Vec4 { return new Vec4(this[0], this[0], this[0], this[2]); }
  /** @group Swizzle */ get xxyx(): Vec4 { return new Vec4(this[0], this[0], this[1], this[0]); }
  /** @group Swizzle */ get xxyy(): Vec4 { return new Vec4(this[0], this[0], this[1], this[1]); }
  /** @group Swizzle */ get xxyz(): Vec4 { return new Vec4(this[0], this[0], this[1], this[2]); }
  /** @group Swizzle */ get xxzx(): Vec4 { return new Vec4(this[0], this[0], this[2], this[0]); }
  /** @group Swizzle */ get xxzy(): Vec4 { return new Vec4(this[0], this[0], this[2], this[1]); }
  /** @group Swizzle */ get xxzz(): Vec4 { return new Vec4(this[0], this[0], this[2], this[2]); }
  /** @group Swizzle */ get xyxx(): Vec4 { return new Vec4(this[0], this[1], this[0], this[0]); }
  /** @group Swizzle */ get xyxy(): Vec4 { return new Vec4(this[0], this[1], this[0], this[1]); }
  /** @group Swizzle */ get xyxz(): Vec4 { return new Vec4(this[0], this[1], this[0], this[2]); }
  /** @group Swizzle */ get xyyx(): Vec4 { return new Vec4(this[0], this[1], this[1], this[0]); }
  /** @group Swizzle */ get xyyy(): Vec4 { return new Vec4(this[0], this[1], this[1], this[1]); }
  /** @group Swizzle */ get xyyz(): Vec4 { return new Vec4(this[0], this[1], this[1], this[2]); }
  /** @group Swizzle */ get xyzx(): Vec4 { return new Vec4(this[0], this[1], this[2], this[0]); }
  /** @group Swizzle */ get xyzy(): Vec4 { return new Vec4(this[0], this[1], this[2], this[1]); }
  /** @group Swizzle */ get xyzz(): Vec4 { return new Vec4(this[0], this[1], this[2], this[2]); }
  /** @group Swizzle */ get xzxx(): Vec4 { return new Vec4(this[0], this[2], this[0], this[0]); }
  /** @group Swizzle */ get xzxy(): Vec4 { return new Vec4(this[0], this[2], this[0], this[1]); }
  /** @group Swizzle */ get xzxz(): Vec4 { return new Vec4(this[0], this[2], this[0], this[2]); }
  /** @group Swizzle */ get xzyx(): Vec4 { return new Vec4(this[0], this[2], this[1], this[0]); }
  /** @group Swizzle */ get xzyy(): Vec4 { return new Vec4(this[0], this[2], this[1], this[1]); }
  /** @group Swizzle */ get xzyz(): Vec4 { return new Vec4(this[0], this[2], this[1], this[2]); }
  /** @group Swizzle */ get xzzx(): Vec4 { return new Vec4(this[0], this[2], this[2], this[0]); }
  /** @group Swizzle */ get xzzy(): Vec4 { return new Vec4(this[0], this[2], this[2], this[1]); }
  /** @group Swizzle */ get xzzz(): Vec4 { return new Vec4(this[0], this[2], this[2], this[2]); }
  /** @group Swizzle */ get yxxx(): Vec4 { return new Vec4(this[1], this[0], this[0], this[0]); }
  /** @group Swizzle */ get yxxy(): Vec4 { return new Vec4(this[1], this[0], this[0], this[1]); }
  /** @group Swizzle */ get yxxz(): Vec4 { return new Vec4(this[1], this[0], this[0], this[2]); }
  /** @group Swizzle */ get yxyx(): Vec4 { return new Vec4(this[1], this[0], this[1], this[0]); }
  /** @group Swizzle */ get yxyy(): Vec4 { return new Vec4(this[1], this[0], this[1], this[1]); }
  /** @group Swizzle */ get yxyz(): Vec4 { return new Vec4(this[1], this[0], this[1], this[2]); }
  /** @group Swizzle */ get yxzx(): Vec4 { return new Vec4(this[1], this[0], this[2], this[0]); }
  /** @group Swizzle */ get yxzy(): Vec4 { return new Vec4(this[1], this[0], this[2], this[1]); }
  /** @group Swizzle */ get yxzz(): Vec4 { return new Vec4(this[1], this[0], this[2], this[2]); }
  /** @group Swizzle */ get yyxx(): Vec4 { return new Vec4(this[1], this[1], this[0], this[0]); }
  /** @group Swizzle */ get yyxy(): Vec4 { return new Vec4(this[1], this[1], this[0], this[1]); }
  /** @group Swizzle */ get yyxz(): Vec4 { return new Vec4(this[1], this[1], this[0], this[2]); }
  /** @group Swizzle */ get yyyx(): Vec4 { return new Vec4(this[1], this[1], this[1], this[0]); }
  /** @group Swizzle */ get yyyy(): Vec4 { return new Vec4(this[1], this[1], this[1], this[1]); }
  /** @group Swizzle */ get yyyz(): Vec4 { return new Vec4(this[1], this[1], this[1], this[2]); }
  /** @group Swizzle */ get yyzx(): Vec4 { return new Vec4(this[1], this[1], this[2], this[0]); }
  /** @group Swizzle */ get yyzy(): Vec4 { return new Vec4(this[1], this[1], this[2], this[1]); }
  /** @group Swizzle */ get yyzz(): Vec4 { return new Vec4(this[1], this[1], this[2], this[2]); }
  /** @group Swizzle */ get yzxx(): Vec4 { return new Vec4(this[1], this[2], this[0], this[0]); }
  /** @group Swizzle */ get yzxy(): Vec4 { return new Vec4(this[1], this[2], this[0], this[1]); }
  /** @group Swizzle */ get yzxz(): Vec4 { return new Vec4(this[1], this[2], this[0], this[2]); }
  /** @group Swizzle */ get yzyx(): Vec4 { return new Vec4(this[1], this[2], this[1], this[0]); }
  /** @group Swizzle */ get yzyy(): Vec4 { return new Vec4(this[1], this[2], this[1], this[1]); }
  /** @group Swizzle */ get yzyz(): Vec4 { return new Vec4(this[1], this[2], this[1], this[2]); }
  /** @group Swizzle */ get yzzx(): Vec4 { return new Vec4(this[1], this[2], this[2], this[0]); }
  /** @group Swizzle */ get yzzy(): Vec4 { return new Vec4(this[1], this[2], this[2], this[1]); }
  /** @group Swizzle */ get yzzz(): Vec4 { return new Vec4(this[1], this[2], this[2], this[2]); }
  /** @group Swizzle */ get zxxx(): Vec4 { return new Vec4(this[2], this[0], this[0], this[0]); }
  /** @group Swizzle */ get zxxy(): Vec4 { return new Vec4(this[2], this[0], this[0], this[1]); }
  /** @group Swizzle */ get zxxz(): Vec4 { return new Vec4(this[2], this[0], this[0], this[2]); }
  /** @group Swizzle */ get zxyx(): Vec4 { return new Vec4(this[2], this[0], this[1], this[0]); }
  /** @group Swizzle */ get zxyy(): Vec4 { return new Vec4(this[2], this[0], this[1], this[1]); }
  /** @group Swizzle */ get zxyz(): Vec4 { return new Vec4(this[2], this[0], this[1], this[2]); }
  /** @group Swizzle */ get zxzx(): Vec4 { return new Vec4(this[2], this[0], this[2], this[0]); }
  /** @group Swizzle */ get zxzy(): Vec4 { return new Vec4(this[2], this[0], this[2], this[1]); }
  /** @group Swizzle */ get zxzz(): Vec4 { return new Vec4(this[2], this[0], this[2], this[2]); }
  /** @group Swizzle */ get zyxx(): Vec4 { return new Vec4(this[2], this[1], this[0], this[0]); }
  /** @group Swizzle */ get zyxy(): Vec4 { return new Vec4(this[2], this[1], this[0], this[1]); }
  /** @group Swizzle */ get zyxz(): Vec4 { return new Vec4(this[2], this[1], this[0], this[2]); }
  /** @group Swizzle */ get zyyx(): Vec4 { return new Vec4(this[2], this[1], this[1], this[0]); }
  /** @group Swizzle */ get zyyy(): Vec4 { return new Vec4(this[2], this[1], this[1], this[1]); }
  /** @group Swizzle */ get zyyz(): Vec4 { return new Vec4(this[2], this[1], this[1], this[2]); }
  /** @group Swizzle */ get zyzx(): Vec4 { return new Vec4(this[2], this[1], this[2], this[0]); }
  /** @group Swizzle */ get zyzy(): Vec4 { return new Vec4(this[2], this[1], this[2], this[1]); }
  /** @group Swizzle */ get zyzz(): Vec4 { return new Vec4(this[2], this[1], this[2], this[2]); }
  /** @group Swizzle */ get zzxx(): Vec4 { return new Vec4(this[2], this[2], this[0], this[0]); }
  /** @group Swizzle */ get zzxy(): Vec4 { return new Vec4(this[2], this[2], this[0], this[1]); }
  /** @group Swizzle */ get zzxz(): Vec4 { return new Vec4(this[2], this[2], this[0], this[2]); }
  /** @group Swizzle */ get zzyx(): Vec4 { return new Vec4(this[2], this[2], this[1], this[0]); }
  /** @group Swizzle */ get zzyy(): Vec4 { return new Vec4(this[2], this[2], this[1], this[1]); }
  /** @group Swizzle */ get zzyz(): Vec4 { return new Vec4(this[2], this[2], this[1], this[2]); }
  /** @group Swizzle */ get zzzx(): Vec4 { return new Vec4(this[2], this[2], this[2], this[0]); }
  /** @group Swizzle */ get zzzy(): Vec4 { return new Vec4(this[2], this[2], this[2], this[1]); }
  /** @group Swizzle */ get zzzz(): Vec4 { return new Vec4(this[2], this[2], this[2], this[2]); }

  // [/Swizzle Autogen]

  //===================
  // Instances methods
  //===================

  /**
   * Adds a {@link Vec3} to `this`.
   * Equivalent to `Vec3.add(this, this, b);`
   * @group Instance
   *
   * @param b - The vector to add to `this`
   * @returns `this`
   */
  add(b: Readonly<Vec3Like>): Vec3 {
    this[0] += b[0];
    this[1] += b[1];
    this[2] += b[2];
    return this;
  }

  /**
   * Subtracts a {@link Vec3} from `this`.
   * Equivalent to `Vec3.subtract(this, this, b);`
   * @group Instance
   *
   * @param b - The vector to subtract from `this`
   * @returns `this`
   */
  subtract(b: Readonly<Vec3Like>): Vec3 {
    this[0] -= b[0];
    this[1] -= b[1];
    this[2] -= b[2];
    return this;
  }

  /**
   * Alias for {@link Vec3.subtract}
   * @group Instance
   */
  sub(b: Readonly<Vec3Like>): Vec3 { return this; }

  /**
   * Multiplies `this` by a {@link Vec3}.
   * Equivalent to `Vec3.multiply(this, this, b);`
   * @group Instance
   *
   * @param b - The vector to multiply `this` by
   * @returns `this`
   */
  multiply(b: Readonly<Vec3Like>): Vec3 {
    this[0] *= b[0];
    this[1] *= b[1];
    this[2] *= b[2];
    return this;
  }

  /**
   * Alias for {@link Vec3.multiply}
   * @group Instance
   */
  mul(b: Readonly<Vec3Like>): Vec3 { return this; }

  /**
   * Divides `this` by a {@link Vec3}.
   * Equivalent to `Vec3.divide(this, this, b);`
   * @group Instance
   *
   * @param b - The vector to divide `this` by
   * @returns `this`
   */
  divide(b: Readonly<Vec3Like>): Vec3 {
    this[0] /= b[0];
    this[1] /= b[1];
    this[2] /= b[2];
    return this;
  }

  /**
   * Alias for {@link Vec3.divide}
   * @group Instance
   */
  div(b: Readonly<Vec3Like>): Vec3 { return this; }

  //================
  // Static methods
  //================

  /**
   * Creates a new, empty vec3
   * @group Static
   *
   * @returns a new 3D vector
   */
  static create(): Vec3 {
    return new Vec3();
  }

  /**
   * Creates a new vec3 initialized with values from an existing vector
   * @group Static
   *
   * @param a - vector to clone
   * @returns a new 3D vector
   */
  static clone(a: Readonly<Vec3Like>): Vec3 {
    return new Vec3(a);
  }

  /**
   * Calculates the length of a vec3
   * @group Static
   * @deprecated Use {@link Vec3.magnitude} to avoid conflicts with builtin `length` methods/attribs
   *
   * @param a - vector to calculate length of
   * @returns length of a
   */
  // @ts-ignore: Length conflicts with Function.length
  static length(a: Readonly<Vec3Like>): number {
    return Vec3.magnitude(a);
  }

  /**
   * Calculates the magnitude (length) of a {@link Vec3}
   * @group Static
   *
   * @param a - vector to calculate length of
   * @returns magnitude of a
   */
  static magnitude(a: Readonly<Vec3Like>): number {
    let x = a[0];
    let y = a[1];
    let z = a[2];
    return Math.sqrt(x * x + y * y + z * z);
  }

  /**
   * Alias for {@link Vec3.magnitude}
   * @group Static
   */
  static mag(a: Readonly<Vec3Like>): number { return 0; }

  /**
   * Creates a new vec3 initialized with the given values
   * @group Static
   *
   * @param x - X component
   * @param y - Y component
   * @param z - Z component
   * @returns a new 3D vector
   */
  static fromValues(x: number, y: number, z: number): Vec3 {
    return new Vec3(x, y, z);
  }

  /**
   * Copy the values from one vec3 to another
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the source vector
   * @returns `out`
   */
  static copy(out: Vec3Like, a: Readonly<Vec3Like>): Vec3Like {
    out[0] = a[0];
    out[1] = a[1];
    out[2] = a[2];
    return out;
  }

  /**
   * Set the components of a vec3 to the given values
   * @group Static
   *
   * @param out - the receiving vector
   * @param x - X component
   * @param y - Y component
   * @param z - Z component
   * @returns `out`
   */
  static set(out: Vec3Like, x: number, y: number, z: number): Vec3Like {
    out[0] = x;
    out[1] = y;
    out[2] = z;
    return out;
  }

  /**
   * Adds two {@link Vec4}s
   * @group Static
   *
   * @param out - The receiving vector
   * @param a - The first operand
   * @param b - The second operand
   * @returns `out`
   */
  static add(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): Vec3Like {
    out[0] = a[0] + b[0];
    out[1] = a[1] + b[1];
    out[2] = a[2] + b[2];
    return out;
  }

  /**
   * Subtracts vector b from vector a
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the first operand
   * @param b - the second operand
   * @returns `out`
   */
  static subtract(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): Vec3Like {
    out[0] = a[0] - b[0];
    out[1] = a[1] - b[1];
    out[2] = a[2] - b[2];
    return out;
  }

  /**
   * Alias for {@link Vec3.subtract}
   * @function
   */
  static sub(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): Vec3Like { return [0, 0, 0]; };

  /**
   * Multiplies two vec3's
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the first operand
   * @param b - the second operand
   * @returns `out`
   */
  static multiply(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): Vec3Like {
    out[0] = a[0] * b[0];
    out[1] = a[1] * b[1];
    out[2] = a[2] * b[2];
    return out;
  }

  /**
   * Alias for {@link Vec3.multiply}
   * @function
   */
  static mul(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): Vec3Like { return [0, 0, 0]; }

  /**
   * Divides two vec3's
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the first operand
   * @param b - the second operand
   * @returns `out`
   */
  static divide(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): Vec3Like {
    out[0] = a[0] / b[0];
    out[1] = a[1] / b[1];
    out[2] = a[2] / b[2];
    return out;
  }

  /**
   * Alias for {@link Vec3.divide}
   * @function
   */
   static div(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): Vec3Like { return [0, 0, 0]; };

  /**
   * Math.ceil the components of a vec3
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - vector to ceil
   * @returns `out`
   */
  static ceil(out: Vec3Like, a: Readonly<Vec3Like>): Vec3Like {
    out[0] = Math.ceil(a[0]);
    out[1] = Math.ceil(a[1]);
    out[2] = Math.ceil(a[2]);
    return out;
  }

  /**
   * Math.floor the components of a vec3
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - vector to floor
   * @returns `out`
   */
  static floor(out: Vec3Like, a: Readonly<Vec3Like>): Vec3Like {
    out[0] = Math.floor(a[0]);
    out[1] = Math.floor(a[1]);
    out[2] = Math.floor(a[2]);
    return out;
  }

  /**
   * Returns the minimum of two vec3's
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the first operand
   * @param b - the second operand
   * @returns `out`
   */
  static min(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): Vec3Like {
    out[0] = Math.min(a[0], b[0]);
    out[1] = Math.min(a[1], b[1]);
    out[2] = Math.min(a[2], b[2]);
    return out;
  }

  /**
   * Returns the maximum of two vec3's
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the first operand
   * @param b - the second operand
   * @returns `out`
   */
  static max(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): Vec3Like {
    out[0] = Math.max(a[0], b[0]);
    out[1] = Math.max(a[1], b[1]);
    out[2] = Math.max(a[2], b[2]);
    return out;
  }

  /**
   * symmetric round the components of a vec3
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - vector to round
   * @returns `out`
   */
  /*static round(out: Vec3Like, a: Readonly<Vec3Like>): Vec3Like {
    out[0] = glMatrix.round(a[0]);
    out[1] = glMatrix.round(a[1]);
    out[2] = glMatrix.round(a[2]);
    return out;
  }*/

  /**
   * Scales a vec3 by a scalar number
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the vector to scale
   * @param scale - amount to scale the vector by
   * @returns `out`
   */
  static scale(out: Vec3Like, a: Readonly<Vec3Like>, scale: number): Vec3Like {
    out[0] = a[0] * scale;
    out[1] = a[1] * scale;
    out[2] = a[2] * scale;
    return out;
  }

  /**
   * Adds two vec3's after scaling the second operand by a scalar value
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the first operand
   * @param b - the second operand
   * @param scale - the amount to scale b by before adding
   * @returns `out`
   */
  static scaleAndAdd(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>, scale: number) {
    out[0] = a[0] + b[0] * scale;
    out[1] = a[1] + b[1] * scale;
    out[2] = a[2] + b[2] * scale;
    return out;
  }

  /**
   * Calculates the euclidian distance between two vec3's
   * @group Static
   *
   * @param a - the first operand
   * @param b - the second operand
   * @returns distance between a and b
   */
  static distance(a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): number {
    const x = b[0] - a[0];
    const y = b[1] - a[1];
    const z = b[2] - a[2];
    return Math.sqrt(x * x + y * y + z * z);
  }

  /**
   * Calculates the squared euclidian distance between two vec3's
   * @group Static
   *
   * @param a - the first operand
   * @param b - the second operand
   * @returns squared distance between a and b
   */
  static squaredDistance(a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): number {
    const x = b[0] - a[0];
    const y = b[1] - a[1];
    const z = b[2] - a[2];
    return x * x + y * y + z * z;
  }

  /**
   * Calculates the squared length of a vec3
   * @group Static
   *
   * @param a - vector to calculate squared length of
   * @returns squared length of a
   */
  static squaredLength(a: Readonly<Vec3Like>): number {
    const x = a[0];
    const y = a[1];
    const z = a[2];
    return x * x + y * y + z * z;
  }

  /**
   * Negates the components of a vec3
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - vector to negate
   * @returns `out`
   */
  static negate(out: Vec3Like, a: Readonly<Vec3Like>): Vec3Like {
    out[0] = -a[0];
    out[1] = -a[1];
    out[2] = -a[2];
    return out;
  }

  /**
   * Returns the inverse of the components of a vec3
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - vector to invert
   * @returns `out`
   */
  static inverse(out: Vec3Like, a: Readonly<Vec3Like>): Vec3Like {
    out[0] = 1.0 / a[0];
    out[1] = 1.0 / a[1];
    out[2] = 1.0 / a[2];
    return out;
  }

  /**
   * Normalize a vec3
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - vector to normalize
   * @returns `out`
   */
  static normalize(out: Vec3Like, a: Readonly<Vec3Like>): Vec3Like {
    const x = a[0];
    const y = a[1];
    const z = a[2];
    let len = x * x + y * y + z * z;
    if (len > 0) {
      //TODO: evaluate use of glm_invsqrt here?
      len = 1 / Math.sqrt(len);
    }
    out[0] = a[0] * len;
    out[1] = a[1] * len;
    out[2] = a[2] * len;
    return out;
  }

  /**
   * Calculates the dot product of two vec3's
   * @group Static
   *
   * @param a - the first operand
   * @param b - the second operand
   * @returns dot product of a and b
   */
  static dot(a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): number {
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
  }

  /**
   * Computes the cross product of two vec3's
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the first operand
   * @param b - the second operand
   * @returns `out`
   */
  static cross(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): Vec3Like {
    const ax = a[0],
      ay = a[1],
      az = a[2];
    const bx = b[0],
      by = b[1],
      bz = b[2];

    out[0] = ay * bz - az * by;
    out[1] = az * bx - ax * bz;
    out[2] = ax * by - ay * bx;
    return out;
  }

  /**
   * Performs a linear interpolation between two vec3's
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the first operand
   * @param b - the second operand
   * @param t - interpolation amount, in the range [0-1], between the two inputs
   * @returns `out`
   */
  static lerp(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>, t: number): Vec3Like {
    const ax = a[0];
    const ay = a[1];
    const az = a[2];
    out[0] = ax + t * (b[0] - ax);
    out[1] = ay + t * (b[1] - ay);
    out[2] = az + t * (b[2] - az);
    return out;
  }

  /**
   * Performs a spherical linear interpolation between two vec3's
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the first operand
   * @param b - the second operand
   * @param t - interpolation amount, in the range [0-1], between the two inputs
   * @returns `out`
   */
  static slerp(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>, t: number): Vec3Like {
    const angle = Math.acos(Math.min(Math.max(Vec3.dot(a, b), -1), 1));
    const sinTotal = Math.sin(angle);

    const ratioA = Math.sin((1 - t) * angle) / sinTotal;
    const ratioB = Math.sin(t * angle) / sinTotal;
    out[0] = ratioA * a[0] + ratioB * b[0];
    out[1] = ratioA * a[1] + ratioB * b[1];
    out[2] = ratioA * a[2] + ratioB * b[2];

    return out;
  }

  /**
   * Performs a hermite interpolation with two control points
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the first operand
   * @param b - the second operand
   * @param c - the third operand
   * @param d - the fourth operand
   * @param t - interpolation amount, in the range [0-1], between the two inputs
   * @returns `out`
   */
  static hermite(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>, c: Readonly<Vec3Like>, d: Readonly<Vec3Like>, t: number): Vec3Like {
    const factorTimes2 = t * t;
    const factor1 = factorTimes2 * (2 * t - 3) + 1;
    const factor2 = factorTimes2 * (t - 2) + t;
    const factor3 = factorTimes2 * (t - 1);
    const factor4 = factorTimes2 * (3 - 2 * t);

    out[0] = a[0] * factor1 + b[0] * factor2 + c[0] * factor3 + d[0] * factor4;
    out[1] = a[1] * factor1 + b[1] * factor2 + c[1] * factor3 + d[1] * factor4;
    out[2] = a[2] * factor1 + b[2] * factor2 + c[2] * factor3 + d[2] * factor4;

    return out;
  }

  /**
   * Performs a bezier interpolation with two control points
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the first operand
   * @param b - the second operand
   * @param c - the third operand
   * @param d - the fourth operand
   * @param t - interpolation amount, in the range [0-1], between the two inputs
   * @returns `out`
   */
  static bezier(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>, c: Readonly<Vec3Like>, d: Readonly<Vec3Like>, t: number): Vec3Like {
    const inverseFactor = 1 - t;
    const inverseFactorTimesTwo = inverseFactor * inverseFactor;
    const factorTimes2 = t * t;
    const factor1 = inverseFactorTimesTwo * inverseFactor;
    const factor2 = 3 * t * inverseFactorTimesTwo;
    const factor3 = 3 * factorTimes2 * inverseFactor;
    const factor4 = factorTimes2 * t;

    out[0] = a[0] * factor1 + b[0] * factor2 + c[0] * factor3 + d[0] * factor4;
    out[1] = a[1] * factor1 + b[1] * factor2 + c[1] * factor3 + d[1] * factor4;
    out[2] = a[2] * factor1 + b[2] * factor2 + c[2] * factor3 + d[2] * factor4;

    return out;
  }

  /**
   * Generates a random vector with the given scale
   * @group Static
   *
   * @param out - the receiving vector
   * @param {Number} [scale] Length of the resulting vector. If omitted, a unit vector will be returned
   * @returns `out`
   */
  /*static random(out: Vec3Like, scale) {
    scale = scale === undefined ? 1.0 : scale;

    let r = glMatrix.RANDOM() * 2.0 * Math.PI;
    let z = glMatrix.RANDOM() * 2.0 - 1.0;
    let zScale = Math.sqrt(1.0 - z * z) * scale;

    out[0] = Math.cos(r) * zScale;
    out[1] = Math.sin(r) * zScale;
    out[2] = z * scale;
    return out;
  }*/

  /**
   * Transforms the vec3 with a mat4.
   * 4th vector component is implicitly '1'
   *
   * @param out - the receiving vector
   * @param a - the vector to transform
   * @param m - matrix to transform with
   * @returns `out`
   */
  static transformMat4(out: Vec3Like, a: Readonly<Vec3Like>, m: Readonly<Mat4Like>): Vec3Like {
    const x = a[0],
      y = a[1],
      z = a[2];
    const w = (m[3] * x + m[7] * y + m[11] * z + m[15]) || 1.0;
    out[0] = (m[0] * x + m[4] * y + m[8] * z + m[12]) / w;
    out[1] = (m[1] * x + m[5] * y + m[9] * z + m[13]) / w;
    out[2] = (m[2] * x + m[6] * y + m[10] * z + m[14]) / w;
    return out;
  }

  /**
   * Transforms the vec3 with a mat3.
   * @group Static
   *
   * @param out - the receiving vector
   * @param a - the vector to transform
   * @param m - the 3x3 matrix to transform with
   * @returns `out`
   */
  /*static transformMat3(out: Vec3Like, a, m) {
    let x = a[0],
      y = a[1],
      z = a[2];
    out[0] = x * m[0] + y * m[3] + z * m[6];
    out[1] = x * m[1] + y * m[4] + z * m[7];
    out[2] = x * m[2] + y * m[5] + z * m[8];
    return out;
  }*/

  /**
   * Transforms the vec3 with a quat
   * Can also be used for dual quaternions. (Multiply it with the real part)
   *
   * @param out - the receiving vector
   * @param a - the vector to transform
   * @param q - quaternion to transform with
   * @returns `out`
   */
  /*static transformQuat(out: Vec3Like, a, q) {
    // benchmarks: https://jsperf.com/quaternion-transform-vec3-implementations-fixed
    let qx = q[0],
      qy = q[1],
      qz = q[2],
      qw = q[3];
    let x = a[0],
      y = a[1],
      z = a[2];
    // var qvec = [qx, qy, qz];
    // var uv = vec3.cross([], qvec, a);
    let uvx = qy * z - qz * y,
      uvy = qz * x - qx * z,
      uvz = qx * y - qy * x;
    // var uuv = vec3.cross([], qvec, uv);
    let uuvx = qy * uvz - qz * uvy,
      uuvy = qz * uvx - qx * uvz,
      uuvz = qx * uvy - qy * uvx;
    // vec3.scale(uv, uv, 2 * w);
    let w2 = qw * 2;
    uvx *= w2;
    uvy *= w2;
    uvz *= w2;
    // vec3.scale(uuv, uuv, 2);
    uuvx *= 2;
    uuvy *= 2;
    uuvz *= 2;
    // return vec3.add(out: Vec3Like, a, vec3.add(out: Vec3Like, uv, uuv));
    out[0] = x + uvx + uuvx;
    out[1] = y + uvy + uuvy;
    out[2] = z + uvz + uuvz;
    return out;
  }*/

  /**
   * Rotate a 3D vector around the x-axis
   * @param out - The receiving vec3
   * @param a - The vec3 point to rotate
   * @param b - The origin of the rotation
   * @param rad - The angle of rotation in radians
   * @returns `out`
   */
  static rotateX(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>, rad: number): Vec3Like {
    let p = [],
      r = [];
    //Translate point to the origin
    p[0] = a[0] - b[0];
    p[1] = a[1] - b[1];
    p[2] = a[2] - b[2];

    //perform rotation
    r[0] = p[0];
    r[1] = p[1] * Math.cos(rad) - p[2] * Math.sin(rad);
    r[2] = p[1] * Math.sin(rad) + p[2] * Math.cos(rad);

    //translate to correct position
    out[0] = r[0] + b[0];
    out[1] = r[1] + b[1];
    out[2] = r[2] + b[2];

    return out;
  }

  /**
   * Rotate a 3D vector around the y-axis
   * @param out - The receiving vec3
   * @param a - The vec3 point to rotate
   * @param b - The origin of the rotation
   * @param rad - The angle of rotation in radians
   * @returns `out`
   */
  static rotateY(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>, rad: number): Vec3Like {
    let p = [],
      r = [];
    //Translate point to the origin
    p[0] = a[0] - b[0];
    p[1] = a[1] - b[1];
    p[2] = a[2] - b[2];

    //perform rotation
    r[0] = p[2] * Math.sin(rad) + p[0] * Math.cos(rad);
    r[1] = p[1];
    r[2] = p[2] * Math.cos(rad) - p[0] * Math.sin(rad);

    //translate to correct position
    out[0] = r[0] + b[0];
    out[1] = r[1] + b[1];
    out[2] = r[2] + b[2];

    return out;
  }

  /**
   * Rotate a 3D vector around the z-axis
   * @param out - The receiving vec3
   * @param a - The vec3 point to rotate
   * @param b - The origin of the rotation
   * @param rad - The angle of rotation in radians
   * @returns `out`
   */
  static rotateZ(out: Vec3Like, a: Readonly<Vec3Like>, b: Readonly<Vec3Like>, rad: number): Vec3Like {
    let p = [],
      r = [];
    //Translate point to the origin
    p[0] = a[0] - b[0];
    p[1] = a[1] - b[1];
    p[2] = a[2] - b[2];

    //perform rotation
    r[0] = p[0] * Math.cos(rad) - p[1] * Math.sin(rad);
    r[1] = p[0] * Math.sin(rad) + p[1] * Math.cos(rad);
    r[2] = p[2];

    //translate to correct position
    out[0] = r[0] + b[0];
    out[1] = r[1] + b[1];
    out[2] = r[2] + b[2];

    return out;
  }

  /**
   * Get the angle between two 3D vectors
   * @param a - The first operand
   * @param b - The second operand
   * @returns The angle in radians
   */
  static angle(a: Readonly<Vec3Like>, b: Readonly<Vec3Like>) {
    const ax = a[0],
      ay = a[1],
      az = a[2],
      bx = b[0],
      by = b[1],
      bz = b[2],
      mag = Math.sqrt((ax * ax + ay * ay + az * az) * (bx * bx + by * by + bz * bz)),
      cosine = mag && Vec3.dot(a, b) / mag;
    return Math.acos(Math.min(Math.max(cosine, -1), 1));
  }

  /**
   * Set the components of a vec3 to zero
   * @group Static
   *
   * @param out - the receiving vector
   * @returns `out`
   */
  static zero(out: Vec3Like): Vec3Like {
    out[0] = 0.0;
    out[1] = 0.0;
    out[2] = 0.0;
    return out;
  }

  /**
   * Returns a string representation of a vector
   * @group Static
   *
   * @param a - vector to represent as a string
   * @returns string representation of the vector
   */
  static str(a: Readonly<Vec3Like>): string {
    return `Vec3(${a.join(', ')})`;
  }

  /**
   * Returns whether or not the vectors have exactly the same elements in the same position (when compared with ===)
   * @group Static
   *
   * @param a - The first vector.
   * @param b - The second vector.
   * @returns True if the vectors are equal, false otherwise.
   */
  static exactEquals(a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): boolean {
    return a[0] === b[0] && a[1] === b[1] && a[2] === b[2];
  }

  /**
   * Returns whether or not the vectors have approximately the same elements in the same position.
   * @group Static
   *
   * @param a - The first vector.
   * @param b - The second vector.
   * @returns True if the vectors are equal, false otherwise.
   */
  static equals(a: Readonly<Vec3Like>, b: Readonly<Vec3Like>): boolean {
    const a0 = a[0],
      a1 = a[1],
      a2 = a[2];
    const b0 = b[0],
      b1 = b[1],
      b2 = b[2];
    return (
      Math.abs(a0 - b0) <=
        EPSILON * Math.max(1.0, Math.abs(a0), Math.abs(b0)) &&
      Math.abs(a1 - b1) <=
        EPSILON * Math.max(1.0, Math.abs(a1), Math.abs(b1)) &&
      Math.abs(a2 - b2) <=
        EPSILON * Math.max(1.0, Math.abs(a2), Math.abs(b2))
    );
  }
}

// Instance method alias assignments
Vec3.prototype.sub = Vec3.prototype.subtract;
Vec3.prototype.mul = Vec3.prototype.multiply;
Vec3.prototype.div = Vec3.prototype.divide;

// Static method alias assignments
Vec3.sub = Vec3.subtract;
Vec3.mul = Vec3.multiply;
Vec3.div = Vec3.divide;
Vec3.mag = Vec3.magnitude;

/**
 * Vec3 alias for backwards compatibility
 */
export const vec3 = Vec3;